'use strict';
let report=JSON.parse(document.getElementById('report-data').textContent);
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=s=>`<span class="badge ${/CHECKED|OBSERVED|EXECUTED|SCANNED|PASS/.test(s)?'pass':/BLOCKED|FAIL|STALE/.test(s)?'fail':''}">${esc(s)}</span>`;
const pretty=x=>JSON.stringify(x,null,2);
const download=(name,text,type)=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
const wrapLabel=label=>{if(label.length<=24)return [label];let cut=label.lastIndexOf(' ',24);if(cut<8)cut=24;const tail=label.slice(cut).trim();return [label.slice(0,cut),tail.length>24?tail.slice(0,23)+'…':tail];};
const panel=(label,body)=>`<h3>${esc(label)}</h3>${body}`;
let view='flow';
function setView(next){view=next;document.querySelectorAll('#views button').forEach(b=>b.classList.toggle('active',b.dataset.view===next));['flow','code','datasets','runs','equations'].forEach(v=>$(v+'-view').hidden=v!==next);if(next==='code')drawCode();}
function graphSvg(nodes,edges,mode){
  if(!nodes.length)return '<p>No nodes in the current view.</p>';
  const ids=new Set(nodes.map(n=>n.id));edges=edges.filter(e=>ids.has(e.from)&&ids.has(e.to));
  const levels=Object.fromEntries(nodes.map(n=>[n.id,0]));
  if(mode==='flow')for(let i=0;i<nodes.length;i++){let changed=false;for(const e of edges){if(levels[e.to]<=levels[e.from]&&levels[e.from]<nodes.length){levels[e.to]=levels[e.from]+1;changed=true;}}if(!changed)break;}
  // Cyclic or very long engineering diagrams use a bounded grid layout.
  const grid=mode==='code'||Math.max(...Object.values(levels))>4;
  const rows={},pos={};
  nodes.forEach((n,i)=>{const col=grid?i%3:levels[n.id],row=grid?Math.floor(i/3):(rows[col]||0);rows[col]=row+1;pos[n.id]=[25+col*197,30+row*93];});
  const width=Math.max(650,...Object.values(pos).map(([x])=>x+192)),height=Math.max(420,...Object.values(pos).map(([,y])=>y+115));
  let html=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" role="img" aria-label="${mode==='code'?'Source dependency graph':'Semantic engineering flow'}"><defs><marker id="eng-arrow-${mode}" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z" fill="#adb9a5"/></marker></defs>`;
  for(const e of edges){const[x,y]=pos[e.from],[xx,yy]=pos[e.to];html+=`<path d="M${x+165},${y+30} C${x+190},${y+30} ${xx-20},${yy+30} ${xx},${yy+30}" stroke="#bcc7b5" fill="none" stroke-width="1.1" marker-end="url(#eng-arrow-${mode})" ${e.evidence==='declared'?'stroke-dasharray="4 3"':''}/>`;}
  for(const n of nodes){const[x,y]=pos[n.id],colors={dataset:['#e3ecf5','#8499ae'],block:['#e4eedf','#91a383'],entity:['#fbf4e5','#bbad8a'],file:['#f4f6ee','#a3af98']},[fill,stroke]=colors[n.kind]||colors.file;const words=wrapLabel(n.label);html+=`<g class="eng-node" data-id="${esc(n.id)}" role="button" tabindex="0" aria-label="${esc(n.label)}"><title>${esc(n.id)}</title><rect x="${x}" y="${y}" width="165" height="61" rx="${n.kind==='dataset'?12:5}" fill="${fill}" stroke="${stroke}"/>${words.map((s,i)=>`<text x="${x+12}" y="${y+20+i*13}" font-family="sans-serif" font-size="10" fill="#29412b">${esc(s)}</text>`).join('')}<text x="${x+12}" y="${y+50}" font-family="monospace" font-size="7.7" fill="#74806d">${esc(n.kind)} · ${esc(n.status||n.repository||n.evidence)}</text></g>`;}
  return html+'</svg>';
}
function bindNodes(container,callback){container.querySelectorAll('.eng-node').forEach(el=>{el.onclick=()=>callback(el.dataset.id);el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();callback(el.dataset.id);}};});}
function inspectNode(id){const n=report.nodes.find(n=>n.id===id);if(!n){$('inspector').textContent='No accepted nodes.';return;}const d=n.detail;let content=`<div class="eyebrow">${esc(n.kind)} / ${esc(n.evidence)}</div><h3>${esc(n.label)}</h3>${badge(n.status)}`;
  if(n.kind==='block'){content+=`<p>${esc(d.meaning)}</p><strong>Declared interfaces</strong><p>Inputs: ${esc((d.inputs||[]).join(', ')||'none')}<br>Outputs: ${esc((d.outputs||[]).join(', ')||'none')}</p><strong>${d.members.length} source files · ${d.executed_members.length} with observed function calls</strong><ul>${d.members.map(f=>`<li><span>${d.executed_members.includes(f)?'●':'○'}</span><code>${esc(f)}</code></li>`).join('')}</ul>`;if(d.equation_evidence?.length)content+=panel('Bound scalar contracts',d.equation_evidence.map(e=>`<p>${esc(e.binding)}<br>${badge(e.proof)} · ${e.executed_samples} samples</p>`).join(''));if(d.parent)content+=`<p>Parent block: ${esc(d.parent)}</p>`;if(d.findings.length)content+=panel('Review paths',d.findings.map(f=>`<p>${esc(f.kind)} at <code>${esc(f.file)}:${f.line}</code></p>`).join(''));content+='<button id="drill-code">Inspect block source graph →</button>';}
  else if(n.kind==='dataset'){content+=`<p>${esc(d.description)}</p><strong>${d.rows_scanned} rows scanned · ${d.columns.length} columns</strong><p>Full scan: ${d.complete}<br>Bytes: ${d.bytes}</p><code>SHA-256 ${esc(d.sha256)}</code><button id="drill-data">Inspect schema and LaTeX →</button>`;}
  else {
    content+=`<p>${esc(d.meaning)}</p><strong>Declared type</strong><p>${esc(d.type)}<br>${esc(d.shape||'')}</p>`;
    if(d.path)content+=`<code>${esc(d.path)}</code><p>Artifact: ${esc(d.artifact_status)}</p><code>${esc(d.sha256||'')}</code>`;
    else content+='<p>Virtual interface. Runtime observations are listed separately under Execution evidence.</p>';
    if(d.shape_check)content+=`<h3>Observed interface check</h3>${badge(d.shape_check.status)}<pre>${esc(pretty(d.shape_check.observations))}</pre>`;
  }
  $('inspector').innerHTML=content;if($('drill-code'))$('drill-code').onclick=()=>{$('block-filter').value=id;setView('code');};if($('drill-data'))$('drill-data').onclick=()=>setView('datasets');
}
function drawFlow(){const flow=report.flows.find(f=>f.id===$('flow-select').value);const selected=new Set(flow?.nodes||report.nodes.map(n=>n.id));const nodes=[...selected].map(id=>report.nodes.find(n=>n.id===id)).filter(Boolean);const edges=report.edges.concat(flow?.edges||[]);$('flow-canvas').innerHTML=graphSvg(nodes,edges,'flow');bindNodes($('flow-canvas'),inspectNode);inspectNode(nodes.find(n=>n.kind==='block')?.id||nodes[0]?.id);}
function drawCode(){let files=report.code?.files||[];const block=report.blocks.find(b=>b.id===$('block-filter').value),repo=$('repo-filter').value;if(block)files=files.filter(f=>block.members.includes(f.id));if(repo)files=files.filter(f=>f.repository===repo);const nodes=files.map(f=>({...f,kind:'file',label:f.path.split('/').slice(-2).join('/')}));const edges=(report.code?.imports||[]).flatMap(e=>e.targets.map(t=>({from:e.from,to:t,evidence:'static'})));$('code-canvas').innerHTML=graphSvg(nodes,edges,'code');$('code-count').textContent=`${files.length} files in this view`;
  bindNodes($('code-canvas'),id=>{const f=report.code.files.find(f=>f.id===id),symbols=report.code.symbols.filter(s=>s.file===id),calls=report.code.calls.filter(c=>c.file===id),observed=report.runs.flatMap(r=>r.trace?.files||[]).filter(o=>o.file===id);$('source-inspector').innerHTML=`<div class="eyebrow">${esc(f.repository)} / STATIC SOURCE</div><h3>${esc(f.path)}</h3>${badge(f.status)}<p>${f.lines} lines · ${symbols.length} definitions<br>${calls.filter(c=>c.resolution==='unresolved').length} unresolved calls</p><code>${esc(f.sha256)}</code>`+panel('Definitions',symbols.map(s=>`<p><code>${esc(s.qualified_name)}:${s.line}</code><br>${esc(s.kind)}</p>`).join(''))+panel('Observed runtime',observed.length?observed.map(o=>`<p>${o.lines.length} lines reached<br>${esc(Object.entries(o.calls).map(([n,k])=>n+' × '+k).join(', '))}</p>`).join(''):'<p>No fresh trace covers this file.</p>')+panel('Static call candidates',calls.slice(0,50).map(c=>`<p><code>${esc(c.name)}:${c.line}</code><br>${esc(c.resolution)}</p>`).join(''));});
}
function renderTables(){
  $('datasets-list').innerHTML=report.datasets.map(d=>`<article class="data-section"><div class="dataset-header"><h3>${esc(d.id)}</h3>${badge(d.status)}</div><p>${esc(d.description)} · ${d.rows_scanned} rows scanned · ${d.complete?'complete file':'partial scan'} · ${d.bytes} bytes</p><table><thead><tr><th>Column</th><th>Observed types</th><th>Missing / scanned</th><th>Numeric range</th></tr></thead><tbody>${d.columns.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.types.join(', '))}</td><td>${c.nulls}/${d.rows_scanned}</td><td>${esc(c.min??'—')} … ${esc(c.max??'—')}</td></tr>`).join('')}</tbody></table><details><summary>Automatically generated LaTeX table</summary><pre>${esc(d.latex)}</pre></details><p><code>SHA-256 ${esc(d.sha256)}</code></p></article>`).join('')||'<p>No datasets selected.</p>';
  $('runs-list').innerHTML=report.runs.map(r=>`<article class="run-section"><div class="dataset-header"><h3>${esc(r.id)}</h3>${badge(r.status)}</div><p>${esc(r.trace?.scope||'No actual run recorded.')}</p>${r.errors.length?`<div class="notice bad">${esc(r.errors.join('; '))}</div>`:''}<p>${r.trace?.files?.length||0} source files observed · ${r.trace?.calls?.length||0} call relationships · ${r.trace?.duration_ms??'—'} ms</p><h3>Declared artifact I/O observed during this run</h3><pre>${esc(pretty(r.trace?.artifact_opens||[]))}</pre><h3>Functions and observed array interfaces</h3><div class="evidence-list">${(r.trace?.files||[]).filter(f=>f.arrays?.length||Object.keys(f.calls).some(n=>n!=='<module>')).map(f=>`<details><summary>${esc(f.file)} · ${f.lines.length} lines reached</summary><pre>${esc(pretty({calls:f.calls,array_arguments:f.arrays,exceptions:f.exceptions}))}</pre></details>`).join('')}</div></article>`).join('')||'<div class="notice">No runs declared. Static scans do not establish execution.</div>';
  $('equations-list').innerHTML=report.equations?.length?report.equations.map(e=>`<article class="data-section"><h3>${esc(e.manifest)}</h3>${badge(e.report.status)}${e.report.contracts.map(c=>`<p>${esc(c.id)} · ${esc(c.proof.status)} · ${c.execution.executed} executed samples</p>`).join('')}</article>`).join(''):'<div class="notice">No scalar equation contracts attached to this engineering manifest. Tensor block meanings and observed runtime shapes carry no real-equivalence proof. Use equation_manifests to attach checkable local kernels.</div>';
}
function render(){
  for(const key of ['nodes','edges','blocks','flows','datasets','runs','equations','errors'])report[key]??=[];
  $('title').textContent=report.title;$('scope').textContent=report.scope;$('status').innerHTML=esc(report.status);$('status').className='badge '+(report.errors.length?'fail':'pass');$('errors').innerHTML=report.errors.map(e=>`<div class="notice bad">${esc(e)}</div>`).join('');const s=report.summary||{};
  $('summary').innerHTML=[['CODEBASES',s.codebases],['SOURCE FILES',s.files],['SEMANTIC BLOCKS',s.blocks],['DATASETS',s.datasets],['EXECUTED RUNS',s.executed_runs]].map(([l,v])=>`<div class="stat"><strong>${v??'—'}</strong><small>${l}</small></div>`).join('');
  $('flow-select').innerHTML='<option value="">All declared entities</option>'+report.flows.map(f=>`<option value="${esc(f.id)}">${esc(f.label||f.id)}</option>`).join('');if(report.flows.length)$('flow-select').value=report.flows[0].id;
  $('block-filter').innerHTML='<option value="">All blocks</option>'+report.blocks.map(b=>`<option value="${esc(b.id)}">${esc(b.label||b.id)}</option>`).join('');$('repo-filter').innerHTML='<option value="">All codebases</option>'+[...new Set((report.code?.files||[]).map(f=>f.repository))].map(id=>`<option>${esc(id)}</option>`).join('');renderTables();drawFlow();setView(view);
}
document.querySelectorAll('#views button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('flow-select').onchange=drawFlow;$('block-filter').onchange=drawCode;$('repo-filter').onchange=drawCode;$('svg-export').onclick=()=>download('engineering-flow.svg',$('flow-canvas').innerHTML,'image/svg+xml');$('export').onclick=()=>download('eqtrace-architecture.json',pretty(report),'application/json');$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>10e6)throw Error('Use an architecture JSON file below 10 MB');const next=JSON.parse(await f.text());if(next.report_kind!=='architecture'||!Array.isArray(next.nodes))throw Error('Expected an EqTrace architecture report');report=next;render();}catch(err){$('errors').textContent=err.message;}};render();
